# Stage 1: Build
FROM node:16 as build
WORKDIR /app

ARG REACT_APP_NAME
ARG REACT_APP_VERSION

ARG REACT_APP_BACKEND_URL
ARG REACT_APP_KEYCLOAK_URL
ARG REACT_APP_KEYCLOAK_REALM
ARG REACT_APP_KEYCLOAK_CLIENT_ID


ENV REACT_APP_NAME=${REACT_APP_NAME}
ENV REACT_APP_VERSION=${REACT_APP_VERSION}

ENV REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
ENV REACT_APP_KEYCLOAK_URL=${REACT_APP_KEYCLOAK_URL}
ENV REACT_APP_KEYCLOAK_REALM=${REACT_APP_KEYCLOAK_REALM}
ENV REACT_APP_KEYCLOAK_CLIENT_ID=${REACT_APP_KEYCLOAK_CLIENT_ID}

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build


# Stage 2: Serve using Nginx
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
